name: Discord GitHub Updates

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.actor }}"
          BRANCH="${GITHUB_REF#refs/heads/}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          REPO="${{ github.repository }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"username\":\"101-Bot\",
            \"embeds\":[
              {
                \"title\":\"🚀 Nova Atualização\",
                \"description\":\"**$COMMIT_MESSAGE**\",
                \"color\":16777215,
                \"fields\":[
                  {
                    \"name\":\"👤 Autor\",
                    \"value\":\"$AUTHOR\",
                    \"inline\":true
                  },
                  {
                    \"name\":\"🌿 Branch\",
                    \"value\":\"$BRANCH\",
                    \"inline\":true
                  },
                  {
                    \"name\":\"📦 Repositório\",
                    \"value\":\"$REPO\"
                  }
                ],
                \"url\":\"$COMMIT_URL\",
                \"footer\":{
                  \"text\":\"1Ø1 Community\"
                },
                \"timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
              }
            ]
          }" \
          "$DISCORD_WEBHOOK_URL"
